config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants, except: [:edit, :update, :destroy] do

   resources :reviews, only: [:new, :create]

  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  CATEGORIES = ["chinese", "italian", "japanese", "french", "belgian"]
  validates :name, presence: true
  validates :address, presence: true
  # validates :phone_number, presence: true
  validates :category, inclusion: { in: CATEGORIES }
end

app/models/review.rb
class Review < ApplicationRecord

  RATING = [0, 1, 2, 3, 4, 5]
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, presence: true
  validates :rating, numericality: true # optional?
  validates :rating, numericality: { greater_than_or_equal_to: 0 }
  validates :rating, numericality: { less_than_or_equal_to: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to @restaurant, notice: 'Restaurant was successfully created.'
    else
      render :new
    end
  end

  # def edit
  #   @restaurant = Restaurant.find(params[:id])
  # end

  # def update
  #   @restaurant = Restaurant.find(params[:id])
  #   if @restaurant.update(restaurant_params)
  #     redirect_to @restaurant, notice: 'Restaurant was successfully updated.'
  #   else
  #     render :edit
  #   end
  # end

  # def destroy

  # end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_numner, :category)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
   @restaurant = Restaurant.find(params[:restaurant_id])
   @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_strong_params)
    @review.restaurant_id = @restaurant.id
    if @review.save
      redirect_to @restaurant, notice: 'Review was successfully created.'
    else
      render :new
    end
  end


  private

  def review_strong_params
    params.require(:review).permit(:rating, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<div class="container" class="col-6-mx-auto">

  <h1>All Restaurants</h1>

  <ul>
  <% @restaurants.each do |restaurant|  %>
    <li class="card">
      <h2><%= link_to restaurant.name, restaurant_path(restaurant) %></h2>
      <h4><%= restaurant.category %></h2>
    </li>
  <% end %>
  </ul>
  <div class="btn">
    <%= link_to "Add restaurant", new_restaurant_path %>
  </div>

</div>

app/views/restaurants/new.html.erb
<h2>Add restaurant</h2>

<%= simple_form_for(@restaurant) do |f| %>

  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.select :category, collection: Restaurant::CATEGORIES %>

  <div class="form-actions btn btn-primary">
    <%= f.button :submit %>
  </div>

<% end %>

<p>
  <%= link_to "Back to list", restaurants_path %>
</p>

app/views/restaurants/show.html.erb
<div class="container" class="col-6-mx-auto">

  <div class="card">

    <h2><%= @restaurant.name %></h2>
    <p>
      <%= @restaurant.address %>
    </p>

    <p>
      <%= @restaurant.phone_number %>
    </p>

    <p>
      <%= @restaurant.category %>
    <p>

    <h5>Reviews:</h5>

    <% @restaurant.reviews.each do |review|  %>
        <p>Rating: <%= review.rating %></p>
        <p><%= review.content %></p>
    <% end %>

    <p>
      <%= link_to "Add Review", new_restaurant_review_path(@restaurant) %>
    </p>

    <p>
      <%= link_to "Back to list", restaurants_path %>
    </p>

  </div>
</div>

app/views/reviews/new.html.erb
<h2>Add Review</h2>

<%= simple_form_for([@restaurant, @review]) do |f| %>

  <p>Rating: </p>
  <%= f.select :rating, collection: Review::RATING %>
  <%= f.input :content %>

  <div class="form-actions btn btn-primary">
    <%= f.button :submit %>
  </div>

<% end %>